# micro1 Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1-deployment
  namespace: cc-aat
  labels:
    app: cc-aat
    component: micro1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-aat
      component: micro1
  template:
    metadata:
      labels:
        app: cc-aat
        component: micro1
    spec:
      containers:
        - name: micro1 # anything
          image: nishsatishbmsce/micro1
          ports:
            - containerPort: 3033
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: micro1-service
  namespace: cc-aat
  labels:
    app: cc-aat
    component: micro1
spec:
  type: ClusterIP
  ports:
    - port: 3033
      protocol: TCP
  selector:
    app: cc-aat
    component: micro1
